//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KmandiliDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeleveryDelay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeleveryDelay()
        {
            this.PastryShopDeleveryMethods = new HashSet<PastryShopDeleveryMethod>();
        }
    
        public int ID { get; set; }
        public int MinDelay { get; set; }
        public int MaxDelay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PastryShopDeleveryMethod> PastryShopDeleveryMethods { get; set; }
    }
}
