//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KmandiliDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastryShopDeleveryMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PastryShopDeleveryMethod()
        {
            this.PastryDeleveryPayments = new HashSet<PastryDeleveryPayment>();
        }
    
        public int ID { get; set; }
        public int PastryShop_FK { get; set; }
        public int DeleveryMethod_FK { get; set; }
        public int DeleveryDelay_FK { get; set; }
    
        public virtual DeleveryDelay DeleveryDelay { get; set; }
        public virtual DeleveryMethod DeleveryMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PastryDeleveryPayment> PastryDeleveryPayments { get; set; }
        public virtual PastryShop PastryShop { get; set; }
    }
}
