//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KmandiliDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PointOfSale()
        {
            this.WorkDays = new HashSet<WorkDay>();
            this.PhoneNumbers = new HashSet<PhoneNumber>();
        }
    
        public int ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int PastryShop_FK { get; set; }
        public int ParkingType_FK { get; set; }
        public int Address_FK { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Parking Parking { get; set; }
        public virtual PastryShop PastryShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDay> WorkDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
    }
}
