//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KmandiliWebService.DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastryDeleveryPayment
    {
        public int ID { get; set; }
        public int PastryShopDeleveryMethod_FK { get; set; }
        public int Payment_FK { get; set; }
    
        public virtual PastryShopDeleveryMethod PastryShopDeleveryMethod { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
